---
-   name: Dependencies
    apt:
        name:
            - apt-transport-https
            - ca-certificates
            - curl
        state: present
        update_cache: yes

-   name: GPG key
    get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc

-   name: Repository
    apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        update_cache: yes

-   name: Docker
    apt:
        name: docker-ce
        state: present
        update_cache: yes
    notify: Start docker on boot

-   name: Docker configuration
    copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
    notify: Reload docker

-   name: Docker prune
    cron:
        name: docker-prune
        job: 'docker system prune -af --filter "until=120h"'
        minute: '0'
        hour: '1'

-   name: Remove useless packages
    apt:
        autoclean: yes

-   name: Remove useless dependencies
    apt:
        autoremove: yes
